steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - ./scripts/display_date.sh
      - $_SRC_REPO_URL
      - $_BRANCH
      - $_REPO
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:     
      - ./scripts/0-checkout.sh
      - $_SRC_REPO_URL
      - $_BRANCH
      - "ANGLES-SSH-KEY"
  - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      - './scripts/1-envi-load.sh'
      - $_REPO
      - $_BRANCH
  - name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args:
      - './build-deploy-firebase/2-build.sh'
      - $_BRANCH
availableSecrets:
    secretManager:
      - versionName: projects/1004695768282/secrets/ANGLES-SSH-KEY/versions/latest
        env: 'SSH_KEY'
options:
  logging: CLOUD_LOGGING_ONLY
